name: macOS

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: macos-latest
    steps:
      - uses: LuisEnMarroquin/setup-ssh-action@v3.0.0
        with:
          SSHKEY: ${{ secrets.SSH_GITHUB }}
      - run: ssh -T git@github.com || true
